env: # 允许的全局变量
  es6: true
  browser: true
  node: true
  jest: true
  mocha: true
  commonjs: true

settings:
  import/resolver:
    node:
      paths:
        - src
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  import/ignore:
    - .js
    - .jsx
    - .ts
    - .tsx

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/typescript
  - airbnb
  - airbnb/hooks
  - plugin:prettier/recommended
  - prettier
  - prettier/@typescript-eslint
  - prettier/react

rules:
  react/jsx-filename-extension:
    - 2
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  import/extensions:
    - 2
    - pattern:
        js: never
        jsx: never
        ts: never
        tsx: never
  react/prop-types: 0
